package javaintervaltimer;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Markus Tuominen 2017
 */
public class JavaIntervalTimer extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	int restCounter = 0;
    int intervalCounter = 0;
    int excerciseCounter = 0;
    String currentExcercise = "";
    
    List<String> listOfMoves = Arrays.asList("Squat", "Crunches", "Push up", "Running Plank", "Burpee", "Back extension");   
    
    public void initialState() {
        startStopButton.setEnabled(true);
        currentActivity.setText("");
        timeField.setText("");
        progressField.setText("");
        currentExcercise = "";
        excerciseCounter = 0;
    }
    
    //First a little bit of rest to get ready for training
    public void restTimer() {
        Timer timer = new Timer();
        restCounter = 10;
        startStopButton.setEnabled(false);
        
        currentActivity.setText("Rest!");

        TimerTask task = new TimerTask() {
            public void run() {
                timeField.setText(Integer.toString(restCounter));
                restCounter--;

                if (restCounter < 10) {
                    timeField.setForeground(Color.red);
                }

                if (restCounter <= -1) {
                    timer.cancel();
                    intervalTimer();
                }
            }
        };
        timer.scheduleAtFixedRate(task, 1000, 1000);
    }

    public void intervalTimer() {
            Timer timer = new Timer();
            intervalCounter = 30; 
            startStopButton.setEnabled(false); // disable button when workout is ongoing. TODO: make it possible to pause workout
                      
            progressField.setText(Integer.toString(excerciseCounter + 1 ) + " / 6");
            
            currentExcercise = listOfMoves.get(excerciseCounter); // get list of moves and show it 
            currentActivity.setText(currentExcercise);

            TimerTask task = new TimerTask() {
                public void run() {
                    timeField.setText(Integer.toString(intervalCounter));
                    intervalCounter--;
                    // change text color depending how much time is left
                    if (intervalCounter < 30) {
                        timeField.setForeground(Color.green);
                    }

                    if (intervalCounter < 20) {
                        timeField.setForeground(Color.yellow);
                    }

                    if (intervalCounter < 10) {
                        timeField.setForeground(Color.red);
                    }

                    if (intervalCounter <= -1) {
                        excerciseCounter++;
                        if (excerciseCounter < 6) {
                            timer.cancel();
                            restTimer(); //if timer is smaller than all of the exercises then just go to the restimer 
                        } else {
                            timer.cancel();
                            initialState(); // else your workout is complete and timer will return to its intitial state
                        }

                    }
                }
            };
            timer.scheduleAtFixedRate(task, 1000, 1000);

    }

    public JavaIntervalTimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the
     * JavaIntervalTimer. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timeField = new javax.swing.JTextField();
        startStopButton = new javax.swing.JButton();
        progressField = new javax.swing.JTextField();
        currentActivity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        timeField.setEditable(false);
        timeField.setBackground(new java.awt.Color(0, 0, 0));
        timeField.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        timeField.setForeground(new java.awt.Color(0, 255, 0));
        timeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timeField.setBorder(null);
        timeField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timeField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        startStopButton.setBackground(new java.awt.Color(0, 255, 0));
        startStopButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        startStopButton.setText("Start");
        startStopButton.setBorder(null);
        startStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });

        progressField.setEditable(false);
        progressField.setBackground(new java.awt.Color(0, 0, 0));
        progressField.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        progressField.setForeground(new java.awt.Color(0, 255, 0));
        progressField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressField.setBorder(null);
        progressField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progressField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        progressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressFieldActionPerformed(evt);
            }
        });

        currentActivity.setEditable(false);
        currentActivity.setBackground(new java.awt.Color(0, 0, 0));
        currentActivity.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        currentActivity.setForeground(new java.awt.Color(0, 255, 0));
        currentActivity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentActivity.setBorder(null);
        currentActivity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        currentActivity.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        currentActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentActivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(currentActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed

        restTimer();
    }//GEN-LAST:event_startStopButtonActionPerformed

    private void progressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressFieldActionPerformed

    private void currentActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentActivityActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaIntervalTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaIntervalTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaIntervalTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaIntervalTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the JavaIntervalTimer */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaIntervalTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentActivity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField progressField;
    private javax.swing.JButton startStopButton;
    private javax.swing.JTextField timeField;
    // End of variables declaration//GEN-END:variables
}
